### PR TITLE
MVP armor block explorer (express + pug + bootstrap)

### PR DESCRIPTION
**Pull request by moshenskyDV**
MVP armor block explorer (express + pug + bootstrap)

### CODE REVIEW

**Comment by username1565** [comment]
To get block by `block_number`, you can use this RPC-call: https://github.com/armornetworkdev/armor/blob/master/docs/Armor-Node-Daemon-JSON-RPC-API.md#2-get_block_header

**Comment by moshenskyDV** [comment]
@username1565 I use info about transactions in the block, it represented only in `get_raw_block`

**Comment by username1565** [comment]
@moshenskyDV, yea but this `RPC-API-call` need the `hash of block` to be `known`.
What in the case, if `block-hash` is `unknown`, but `block-number`, where `transaction` was been included, is `known`?

All right, need just to get `block-hash` by `block-number`, using `get_block_header`,
and do this before run `get_raw_block`.
I do not know, how to coding this, maybe you know.

**Comment by username1565** [comment]
@moshenskyDV , really, `get_raw_block` RPC-call, can accept `height_or_depth`: https://github.com/moshenskyDV/armor-explorer/pull/1

**Pull request merged**
